### ISSUE TITLE
Dev install: bower_components needed in src/kibana

### ISSUE THREAD

**Issue by jdrews** [LucidWorks/silk#3]
Ticket is to update install steps from dev. 

After doing `bower install` it created bower_components folder. Then I had to copy bower_components to src/kibana since `grunt build` was looking for it there. Then `grunt build` completed (but with Warnings). 

```
[root@drewstest silk]# grunt --version
grunt-cli v0.1.13
grunt v0.4.5
[root@drewstest silk]# bower --version
1.6.5
[root@drewstest silk]# npm --version
2.11.3
[root@drewstest silk]# node --version
v0.12.7
[root@drewstest silk]# grunt build --debug
Running "get_build_props" task
[D] Task source: tasks/get_build_props.js
Warning: Process exitted with non-zero code 128 Use --force to continue.

Aborted due to warnings.
[root@drewstest silk]# grunt build --debug --force
Running "get_build_props" task
[D] Task source: tasks/get_build_props.js
Warning: Process exitted with non-zero code 128 Used --force, continuing.

Running "clean:target" (clean) task
[D] Task source: /usr/local/silk/node_modules/grunt-contrib-clean/tasks/clean.js

Running "clean:build" (clean) task
[D] Task source: /usr/local/silk/node_modules/grunt-contrib-clean/tasks/clean.js
Cleaning /usr/local/silk/build...OK

Running "require_css_deps:copy" task
[D] Task source: tasks/require_css_deps.js
Warning: Unable to read "/usr/local/silk/src/kibana/bower_components/require-css/css-builder.js" file (Error code: ENOENT). Used --force, continuing.

Running "less:src" (less) task
[D] Task source: /usr/local/silk/node_modules/grunt-contrib-less/tasks/less.js
>> FileError: 'lesshat.less' wasn't found in /usr/local/silk/src/kibana/components/agg_table/agg_table.less on line 1, column 1:
>> 1 @import (reference) "lesshat.less";
>> 2 @import (reference) "../../styles/theme/_variables.less";
Warning: Error compiling /usr/local/silk/src/kibana/components/agg_table/agg_table.less Used --force, continuing.
>> TypeError: Cannot read property 'toCSS' of undefined
>>   at minify (/usr/local/silk/node_modules/grunt-contrib-less/tasks/less.js:173:16)
>>   at /usr/local/silk/node_modules/grunt-contrib-less/tasks/less.js:141:15
>>   at Object.finish [as _finish] (/usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/parser.js:666:28)
>>   at Object.subFinish [as _finish] (/usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/import-visitor.js:87:47)
>>   at Object.subFinish [as _finish] (/usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/import-visitor.js:87:47)
>>   at Object.tree.importVisitor.run (/usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/import-visitor.js:34:22)
>>   at /usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/import-visitor.js:98:38
>>   at fileParsedFunc (/usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/parser.js:82:17)
>>   at /usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/parser.js:105:29
>>   at finish (/usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/parser.js:669:28)
>>   at Object.Parser.parser.parse [as parse] (/usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/parser.js:677:24)
>>   at /usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/parser.js:104:50
>>   at handleDataAndCallCallback (/usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/index.js:161:9)
>>   at /usr/local/silk/node_modules/grunt-contrib-less/node_modules/less/lib/less/index.js:241:37
>>   at process._tickCallback (node.js:355:11)
Warning: Error compiling /usr/local/silk/src/kibana/components/agg_table/agg_table.less Used --force, continuing.

Running "copy:kibana_src" (copy) task
[D] Task source: /usr/local/silk/node_modules/grunt-contrib-copy/tasks/copy.js
Created 134 directories, copied 584 files

Done, but with warnings.
```

Then I copied bower_components and `grunt build` finished. 

```
[root@drewstest silk]# ls
bower_components  bower.json  build  CONTRIBUTING.md  docs  FAQ.md  Gruntfile.js  LICENSE.md  node_modules  package.json  README.md  silkconfig  src  STYLEGUIDE.md  tasks  test
[root@drewstest silk]# cp -ra bower_components src/kibana/
[root@drewstest silk]# grunt build --debug
Running "get_build_props" task
[D] Task source: tasks/get_build_props.js
Warning: Process exitted with non-zero code 128 Use --force to continue.

Aborted due to warnings.
[root@drewstest silk]# grunt build --debug --force
Running "get_build_props" task
[D] Task source: tasks/get_build_props.js
Warning: Process exitted with non-zero code 128 Used --force, continuing.

Running "clean:target" (clean) task
[D] Task source: /usr/local/silk/node_modules/grunt-contrib-clean/tasks/clean.js

Running "clean:build" (clean) task
[D] Task source: /usr/local/silk/node_modules/grunt-contrib-clean/tasks/clean.js
Cleaning /usr/local/silk/build...OK

Running "require_css_deps:copy" task
[D] Task source: tasks/require_css_deps.js

Running "less:src" (less) task
[D] Task source: /usr/local/silk/node_modules/grunt-contrib-less/tasks/less.js
File /usr/local/silk/src/kibana/components/agg_table/agg_table.css created.
File /usr/local/silk/src/kibana/components/collapsible_sidebar/collapsible_sidebar.css created.
File /usr/local/silk/src/kibana/components/doc_table/doc_table.css created.
File /usr/local/silk/src/kibana/components/doc_viewer/doc_viewer.css created.
File /usr/local/silk/src/kibana/components/filter_bar/filter_bar.css created.
File /usr/local/silk/src/kibana/components/typeahead/typeahead.css created.
File /usr/local/silk/src/kibana/components/visualize/visualize.css created.
File /usr/local/silk/src/kibana/styles/main.css created.
File /usr/local/silk/src/kibana/components/vislib/styles/main.css created.
File /usr/local/silk/src/kibana/plugins/dashboard/styles/main.css created.
File /usr/local/silk/src/kibana/plugins/discover/styles/main.css created.
File /usr/local/silk/src/kibana/plugins/settings/styles/main.css created.
File /usr/local/silk/src/kibana/plugins/visualize/styles/main.css created.
File /usr/local/silk/src/kibana/plugins/table_vis/table_vis.css created.
File /usr/local/silk/src/kibana/plugins/metric_vis/metric_vis.css created.
File /usr/local/silk/src/kibana/plugins/markdown_vis/markdown_vis.css created.

Running "copy:kibana_src" (copy) task
[D] Task source: /usr/local/silk/node_modules/grunt-contrib-copy/tasks/copy.js
Created 262 directories, copied 2787 files

Done, but with warnings.
```

**Comment by athana** [comment]
Ok, let me take a look at this issue.

**Comment by arijitdasgupta** [comment]
@jdrews You would also need to do `bower install` to install the front-end dependencies. `grunt build` doesn't do that. You would have to do that separately.

``` bash
npm install -g bower #globally install bower
bower install
```

**Comment by arijitdasgupta** [comment]
Closing this issue as it's a related to missing dependency installation...
