### ISSUE TITLE
Silk is loading screen....

### ISSUE THREAD

**Issue by rohanganpatye** [LucidWorks/silk#7]
Hi @athana  

So I followed the installation instructions to set up Silk as pointed in the repo. I have 2 solr instances running locally on 2 different ports (localhost:7700 and 8800) with an external zookeeper instance. I also 1 collection already created across these 2 instances. 

Now when I do -- npm run start and point my browser to localhost:5601, I'm stuck at the following screen (ref. attachment).
![screen shot 2016-04-11 at 3 21 26 pm](https://cloud.githubusercontent.com/assets/2896203/14444287/65a43c88-fff9-11e5-89b9-945e0ffc9d3f.png)

Can you please advise what is it that I'm missing here?

**Comment by rohanganpatye** [comment]
@

**Comment by samirabdou** [comment]
@rohanganpatye which version of solr are you running ?  I am running  in the same problem.

**Comment by arijitdasgupta** [comment]
@rohanganpatye looks like the dependencies aren't loading. Is it built properly? Could you post some browser console output?

Thanks

**Comment by rohanganpatye** [comment]
@arijitdasgupta I followed the setup instructions exactly as outlined on the GitHub page.

**Comment by smourph** [comment]
I have the same issue.
`npm run start` do a `npm install` then run kibana, so all the front dependencies are missing.

When I manually run `bower install`, I got errors with lodash-deep package: 
- the required version (spenceralger/lodash-deep#compat) no longer exist ;
- other versions (https://github.com/spalger/lodash-deep / https://github.com/marklagendijk/lodash-deep) doesn't work : `bower_components/lodash-deep/factory.js` is missing in front...

When I manually run `grunt build`, I got errors with lesshat (lesshat.less is missing in its bower_components folder).

Grunt error log:

> (node:8995) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
> Running "get_build_props" task
> Warning: Process exitted with non-zero code 128 Used --force, continuing.
> 
> Running "clean:target" (clean) task
> 
> Running "clean:build" (clean) task
> Cleaning /opt/silk/build...OK
> 
> Running "require_css_deps:copy" task
> 
> Running "less:src" (less) task
> 
> > > FileError: '../../bower_components/lesshat/lesshat.less' wasn't found in /opt/silk/src/kibana/components/agg_table/agg_table.less on line 1, column 1:
> > > 1 @import '../../bower_components/lesshat/lesshat.less';
> > > 2 @import (reference) "../../styles/theme/_variables.less";
> > > Warning: Error compiling /opt/silk/src/kibana/components/agg_table/agg_table.less Used --force, continuing.
> > > TypeError: Cannot read property 'toCSS' of undefined
> > >   at minify (/opt/silk/node_modules/grunt-contrib-less/tasks/less.js:173:16)
> > >   at /opt/silk/node_modules/grunt-contrib-less/tasks/less.js:141:15
> > >   at Object.finish [as _finish](/opt/silk/node_modules/less/lib/less/parser.js:666:28)
> > >   at Object.subFinish [as _finish](/opt/silk/node_modules/less/lib/less/import-visitor.js:87:47)
> > >   at Object.subFinish [as _finish](/opt/silk/node_modules/less/lib/less/import-visitor.js:87:47)
> > >   at Object.tree.importVisitor.run (/opt/silk/node_modules/less/lib/less/import-visitor.js:34:22)
> > >   at /opt/silk/node_modules/less/lib/less/import-visitor.js:98:38
> > >   at fileParsedFunc (/opt/silk/node_modules/less/lib/less/parser.js:82:17)
> > >   at /opt/silk/node_modules/less/lib/less/parser.js:105:29
> > >   at finish (/opt/silk/node_modules/less/lib/less/parser.js:669:28)
> > >   at Object.Parser.parser.parse [as parse](/opt/silk/node_modules/less/lib/less/parser.js:677:24)
> > >   at /opt/silk/node_modules/less/lib/less/parser.js:104:50
> > >   at handleDataAndCallCallback (/opt/silk/node_modules/less/lib/less/index.js:161:9)
> > >   at /opt/silk/node_modules/less/lib/less/index.js:241:37
> > >   at _combinedTickCallback (internal/process/next_tick.js:67:7)
> > >   at process._tickCallback (internal/process/next_tick.js:98:9)
> > > Warning: Error compiling /opt/silk/src/kibana/components/agg_table/agg_table.less Used --force, continuing.
> 
> Running "copy:kibana_src" (copy) task
> Created 347 directories, copied 3062 files
> 
> Done, but with warnings.

Thanks for help

**Comment by DarkFisk** [comment]
Did you solve this issue? I have the same problem, after same manipulation I move to next page, but there is no any styles, and I can see in browser console that many of styles and etc. not loaded with 404 error (for instance "main.css")
